name: Release & Publish

on:
  release:
    types:
      - published

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-22.04

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Validate vss-extension version matches release tag
        run: |
          VERSION=$(cat vss-extension.json | jq -r .version)
          if [ "v$VERSION" != "${GITHUB_REF/refs\/tags\//}" ]; then
            echo "Version mismatch: vss-extension.json version is $VERSION, but release tag is ${GITHUB_REF/refs\/tags\//}"
            exit 1
          fi

  publish:
    runs-on: ubuntu-22.04
    needs: validate
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Install modules
        run: npm install
      - name: Install talk modules
        working-directory: ./task
        run: npm install
      - name: Build task
        working-directory: ./task
        run: npm run build
      - name: Package extension
        run: npm run package
      - name: Publish extension
        run: PAT=${{ secrets.AZURE_DEVOPS_MARKETPLACE_PAT }} npm run publish
